language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# command to install dependencies
install:
  - pip install git+git://github.com/ewels/MultiQC.git
  - python setup.py -q install
  - git clone https://github.com/ewels/MultiQC_TestData.git test_data
  - cd test_data
# command to run tests
script:
  - multiqc data -t ngi
  - multiqc data -f -t genstat
