#
# MuiltiQC NGI Example Config
#

# This is an example MultiQC NGI config file.
# These settings should be added to a MultiQC config file:
# - <MQC_installation_dir>/multiqc_config.yaml
# - ~/multiqc_config.yaml
# - Specify a path with -c

# NB: This is NOT the config file that is used in production,
# it is only an example config to keep track of useful settings.

template: 'ngi'
push_statusdb: True
extra_fn_clean_exts:
    - .bowtie_log
    - .featureCounts
fn_ignore_paths:
    - '*/piper_ngi/01_raw_alignments/*'
    - '*/piper_ngi/02_preliminary_alignment_qc/*'
    - '*/piper_ngi/03_genotype_concordance/*'
    - '*/piper_ngi/04_merged_alignments/*'

save_remote: True
remote_sshkey: '~/.ssh/id_rsa'  # Optional
remote_port: '5912'             # Optional
remote_destination: 'genomics.www@tools.scilifelab.se:/var/local/mqc_reports/'
