#
# MuiltiQC NGI Example Config
#

# This is an example MultiQC config file.
# These settings should be added to a MultiQC config file:
# - <MQC_installation_dir>/multiqc_config.yaml
# - ~/multiqc_config.yaml
# - Specify a path with -c

fn_ignore_paths:
    - '*/piper_ngi/01_raw_alignments'
    - '*/piper_ngi/02_preliminary_alignment_qc'
    - '*/piper_ngi/03_genotype_concordance'
    - '*/piper_ngi/04_merged_alignments'